---
## If you have installed the CRDs manually instead of with the `--set installCRDs=true` option added to your Helm install command, you should upgrade your CRD resources before upgrading the Helm chart:
#PROXY_PREFIX="https:/"
#PROXY_PREFIX="https://nexus.home.dgkncgty.com/repository"
#kubectl apply -f $PROXY_PREFIX/github.com/jetstack/cert-manager/releases/download/v1.5.1/cert-manager.crds.yaml
#
## Add the Jetstack Helm repository
#helm repo add jetstack $PROXY_PREFIX/charts.jetstack.io
#helm repo update
#
## Install the cert-manager Helm chart
#helm install cert-manager jetstack/cert-manager \
#  --namespace cert-manager \
#  --create-namespace \
#  --version v1.5.1

- name: Download CRD settings manifest to the cluster
  ansible.builtin.get_url:
    url: "{{ crd_install_yaml_url }}"
    dest: /tmp/crd-settings.yaml
    timeout: 60
    mode: '0664'

- name: Apply CRD settings
  kubernetes.core.k8s:
    state: present
    src: /tmp/crd-settings.yaml

- name: Add cert-manager helm chart
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "{{ cert_manager_helm_chart }}"

- name: Install cert-manager from helm chart
  kubernetes.core.helm:
    name: "{{ cert_manager_release_name }}"
    chart_ref: jetstack/cert-manager
    chart_version: "v{{ cert_manager_chart_version }}"
    release_namespace: "{{ cert_manager_release_namespace }}"
    create_namespace: true

# - name: Apply CRD settings
#   ansible.builtin.shell: /var/lib/rancher/rke2/bin/kubectl apply -f {{ crd_install_yaml_url }}
# - name: Add cert-manager helm chart
  # ansible.builtin.shell: |
  #   helm repo add jetstack {{ cert_manager_helm_chart }}
  #   helm repo update
# - name: Install cert-manager from helm chart
  # ansible.builtin.shell: |
  #   helm install cert-manager jetstack/cert-manager \
  #     --namespace {{ cert_manager_namespace }} \
  #     --create-namespace \
  #     --version v{{ cert_manager_version }}
